services:

  video-processing:
    build: .
    ports:
      - "8080:8080" # Flask HTTP Server
      - "8000:8000" # Prometheus Server
    environment:
      - FLASK_ENV=development
      #      - PYTHONUNBUFFERED=0 # Always flushes out
      - DOCKER_SOCKET_PATH=/var/run/docker.sock # /home/boris/.docker/desktop/docker.sock
      - DOCKER_PREFIX=unix:// # npipe://
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Need to map the host socket into the container so that the client can access it
  #    restart: always


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - /home/boris/development/multiScaler/prometheus.yml:/etc/prometheus/prometheus.yml # Linux
#      - /c/users/boris/development/multiScaler/prometheus.yml:/etc/prometheus/prometheus.yml # Windows
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminadmin
