version: '3.8'

services:
  video-processing:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
#    volumes:
#      - .:/app
    restart: always


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /c/users/boris/development/multiScaler/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminadmin
#    volumes:
#      - grafana-storage:/var/lib/grafana
