global:
  scrape_interval: 500ms


scrape_configs:

  - job_name: 'iot_service'
    static_configs:
      - targets: [ '172.18.0.1:8000','host.docker.internal:8000' ] #, 'host.docker.internal:8000' ] # host.docker.internal:8000
