global:
  scrape_interval: 400ms


scrape_configs:

  - job_name: 'iot_service'
    static_configs:
      - targets: [ '172.17.0.1:8000', '172.18.0.1:8000', '172.19.0.1:8000','host.docker.internal:8000'] #, 'host.docker.internal:8000' ] # host.docker.internal:8000
